ARG FRONTEND_IMAGE=conikuvat/edegal-frontend
FROM $FRONTEND_IMAGE
USER root
RUN node_modules/.bin/react-scripts-ts build && find build -type f \! -iname '*.gz' -exec gzip -k \{\} +

FROM nginx:1-alpine
COPY --from=0 /usr/src/app/build /usr/share/nginx/html

