version: '2.2'
services:
  backend:
    build: backend
    init: true
    command: scripts/wait-for-it.sh --timeout=60 --strict postgres:5432 -- scripts/wait-for-it.sh --timeout=60  --strict redis:6379 -- python manage.py docker_start
    ports:
      - 8000:8000
    links:
      - redis
      - postgres
      - memcache
    volumes:
      - ./backend/edegal:/usr/src/app/edegal
      - media:/usr/src/app/media
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: psql://edegal:edegal@postgres/edegal
      ALLOWED_HOSTS: '*'
      BROKER_URL: redis://redis:6379
      CACHE_URL: memcache://memcache
  worker:
    build: backend
    init: true
    command: scripts/wait-for-it.sh --timeout=60 --strict postgres:5432 -- scripts/wait-for-it.sh --timeout=60  --strict redis:6379 -- celery -A edegal_site.celery:app worker
    links:
      - redis
      - postgres
      - memcache
    volumes:
      - ./backend/edegal:/usr/src/app/edegal
      - media:/usr/src/app/media
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: psql://edegal:edegal@postgres/edegal
      ALLOWED_HOSTS: '*'
      BROKER_URL: redis://redis:6379
      CACHE_URL: memcache://memcache
  frontend:
    build: frontend
    init: true
    ports:
      - 3000:3000
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      REACT_APP_EDEGAL_LOGIN_URL: http://localhost:8000/admin/
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: edegal
      POSTGRES_PASSWORD: edegal
      POSTGRES_DB: edegal
  redis:
    image: redis
  memcache:
    image: memcached
volumes:
  postgres-data: {}
  media: {}
