FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt requirements-production.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt -r requirements-production.txt
COPY . /usr/src/app
RUN env DEBUG=1 python manage.py collectstatic --noinput && \
    python -m compileall -q .
EXPOSE 8000
VOLUME /usr/src/app/media
CMD ["python", "manage.py", "docker_start"]
