version: '2.2'
services:
  backend:
    build: backend
    init: true
    command: scripts/wait-for-it.sh --timeout=60 --strict postgres:5432 -- scripts/wait-for-it.sh --timeout=60  --strict redis:6379 -- python manage.py docker_start
    ports:
      - 8000:8000
    volumes:
      - ./backend/edegal:/usr/src/app/edegal
      - ./backend/larppikuvat:/usr/src/app/larppikuvat
      - media:/usr/src/app/media
    environment: &environment
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: psql://edegal:edegal@postgres/edegal
      ALLOWED_HOSTS: '*'
      BROKER_URL: redis://redis/0
      CACHE_URL: redis://redis/1
      EDEGAL_ENABLE_LARPPIKUVAT_FEATURES: "true"
  worker:
    build: backend
    init: true
    command: scripts/wait-for-it.sh --timeout=60 --strict postgres:5432 -- scripts/wait-for-it.sh --timeout=60  --strict redis:6379 -- celery -A edegal_site.celery:app worker
    volumes:
      - ./backend/edegal:/usr/src/app/edegal
      - ./backend/larppikuvat:/usr/src/app/larppikuvat
      - media:/usr/src/app/media
    environment:
      <<: *environment
  frontend:
    build: frontend
    init: true
    command:
      - node_modules/.bin/vite
      - --host=0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
    tmpfs:
      - /usr/src/app/node_modules/.cache
      - /usr/src/app/node_modules/.vite
    environment:
      VITE_EDEGAL_PROXY_URL: http://backend:8000
      VITE_EDEGAL_LOGIN_URL: http://localhost:8000/admin/
      CI: "true"
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: edegal
      POSTGRES_PASSWORD: edegal
      POSTGRES_DB: edegal
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  postgres-data: {}
  redis-data: {}
  media: {}
