apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: edegal

build:
  local:
    useBuildkit: true
  artifacts:
    - image: edegal
      context: backend

deploy:
  kubectl:
    manifests:
      - kubernetes/template.compiled.yaml
