apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    {{- include "v4.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      stack: v4
      component: nginx
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
      labels:
        stack: v4
        component: nginx
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1082
        runAsGroup: 1082
        fsGroup: 1082
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1-alpine
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: true
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: media
          nfs:
            server: {{ .Values.mediaNfs.server }}
            path: {{ .Values.mediaNfs.path }}
            readOnly: true
        - name: config
          configMap:
            name: nginx
