{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: v4
  labels:
    {{- include "v4.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc }}
  AUTH_SECRET: {{ .Values.secret.authSecret | b64enc }}
  KOMPASSI_OIDC_CLIENT_ID: {{ .Values.secret.kompassiClientId | b64enc }}
  KOMPASSI_OIDC_CLIENT_SECRET: {{ .Values.secret.kompassiClientSecret | b64enc }}
{{- end }}
