apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    stack: edegal
    component: memcached
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    stack: edegal
    component: memcached
