# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_is_public'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
