apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      stack: edegal
      component: celery
  template:
    metadata:
      labels:
        stack: edegal
        component: celery
    spec:
      enableServiceLinks: false
      containers:
        - name: master
          image: !Var edegal_image
          args: ["celery", "-A", "edegal_site.celery:app", "worker"]
          env: !Var edegal_environment
          volumeMounts:
            - mountPath: /usr/src/app/media
              name: edegal-media
      volumes: !Var edegal_media_volumes_definition
