apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  selector:
    matchLabels:
      stack: edegal
      component: celery
  template:
    metadata:
      labels:
        stack: edegal
        component: celery
    spec:
      enableServiceLinks: false
      securityContext: !Var edegal_pod_security_context
      containers:
        - name: celery
          image: !Var edegal_image
          args: ["celery", "-A", "edegal_site.celery:app", "worker"]
          env: !Var edegal_environment
          volumeMounts: !Var edegal_media_volume_mounts
          securityContext: !Var edegal_container_security_context
      volumes: !Var edegal_media_volumes_definition
