apiVersion: v1
kind: ConfigMap
metadata:
  name: v4
  labels:
    {{- include "v4.labels" . | nindent 4 }}
data:
  AUTH_URL: {{ printf "https://%s" .Values.hostname | quote }}
  MEDIA_ROOT: /usr/src/app/media
  MEDIA_BASE_URL: /media
  KOMPASSI_BASE_URL: {{ .Values.kompassi.baseUrl | quote }}
  PHOTOGRAPHER_GROUP: {{ .Values.kompassi.photographerGroup | quote }}
  ADMIN_GROUP: {{ .Values.kompassi.adminGroup | quote }}
  LEGACY_ENABLED: "true"
  LEGACY_ADMIN_URL: {{ .Values.legacyAdminUrl | quote }}
  SMTP_HOSTNAME: {{ .Values.mail.smtpHostname | quote }}
  SMTP_PORT: {{ .Values.mail.smtpPort | quote }}
  MAIL_SENDER: {{ .Values.mail.sender | quote }}
  FORMATTED_MAIL_FROM: {{ .Values.mail.from | quote }}
