apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      stack: edegal
      component: rabbitmq
  template:
    metadata:
      labels:
        stack: edegal
        component: rabbitmq
    spec:
      containers:
        - name: master
          image: !Var rabbitmq_image
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              value: !Var rabbitmq_vhost
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: username
          volumeMounts:
            - !If
                test: !Var rabbitmq_enable_volumes
                then:
                  mountPath: /var/lib/rabbitmq
                  name: rabbitmq-data
      volumes:
        - !If
            test: !Var rabbitmq_enable_volumes
            then:
              name: rabbitmq-data
              persistentVolumeClaim:
                claimName: rabbitmq-data
