apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    stack: edegal
    component: rabbitmq
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
data:
  username: !Base64 edegal
