apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    stack: edegal
    component: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    stack: edegal
    component: rabbitmq
