apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: edegal
      component: nginx
  template:
    metadata:
      labels:
        stack: edegal
        component: nginx
    spec:
      containers:
        - name: master
          image: !Var edegal_static_image
          ports:
            - containerPort: 80
          volumeMounts:
            - !If
                test: !Var edegal_enable_volumes
                then:
                  mountPath: /usr/share/nginx/html/media
                  name: edegal-media
      volumes:
        - !If
            test: !Var edegal_enable_volumes
            then:
              name: edegal-media
              persistentVolumeClaim:
                claimName: edegal-media
