apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: edegal
      component: nginx
  template:
    metadata:
      labels:
        stack: edegal
        component: nginx
    spec:
      enableServiceLinks: false
      containers:
        - name: nginx
          image: !Var edegal_static_image
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/media
              name: edegal-media
      volumes: !Var edegal_media_volumes_definition
