apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: edegal
    component: redis
  name: redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
