ingress_public_hostname: beta.conikuvat.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: conikuvat
postgres_username: conikuvat

redis_image: redis:6.0.8-buster
redis_storage_pvc: true
redis_storage_pvc_storageclass: longhorn

edegal_repository: harbor.con2.fi/con2/edegal
edegal_tag: latest
edegal_storage_pvc: false
edegal_storage_nfs: 91.105.251.66

setup_should_run: false

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
