ingress_public_hostname: dev.conikuvat.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: conikuvatdev
postgres_username: conikuvatdev
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 1
redis_cache_database: 1

edegal_repository: harbor.con2.fi/con2/edegal
edegal_tag: staging
edegal_storage_pvc: true
edegal_storage_pvc_storageclass: longhorn-nfs
edegal_storage_nfs: false

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
