apiVersion: apps/v1
kind: Deployment
metadata:
  name: edegal
spec:
  selector:
    matchLabels:
      stack: edegal
      component: edegal
  template:
    metadata:
      labels:
        stack: edegal
        component: edegal
    spec:
      containers:
        - name: master
          image: !Var edegal_image
          ports:
            - containerPort: 8000
          env: !Var edegal_environment
          readinessProbe:
            httpGet:
              path: /api/v3/status
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/v3/status
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - !If
                test: !Any [!Var edegal_storage_pvc, !Var edegal_storage_cephfs]
                then:
                  mountPath: /usr/src/app/media
                  name: edegal-media
      volumes:
        - !If
            test: !Var edegal_storage_pvc
            then:
              name: edegal-media
              persistentVolumeClaim:
                claimName: edegal-media
        - !If
            test: !Var edegal_storage_cephfs
            then: !Var edegal_storage_cephfs_volume_definition
