apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: edegal
    component: edegal
  name: edegal-media
spec:
  storageClassName: !Var edegal_storage_pvc_storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
