apiVersion: v1
kind: Secret
metadata:
  name: edegal
  labels:
    stack: edegal
  annotations: !If
    test: !Not,Var edegal_secret_key
    then:
      secret-generator.v1.mittwald.de/autogenerate: secretKey
type: Opaque
data: !If
  test: !Var edegal_secret_key
  then:
    secretKey: !Base64,Var edegal_secret_key
  else: {}