apiVersion: v1
kind: Service
metadata:
  name: edegal
  labels:
    stack: edegal
    component: edegal
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    stack: edegal
    component: edegal
