# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 10:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import edegal.models.terms_and_conditions
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, help_text='Tekninen nimi eli "slug" näkyy URL-osoitteissa. Sallittuja merkkejä ovat pienet kirjaimet, numerot ja väliviiva. Jos jätät teknisen nimen tyhjäksi, se generoidaan automaattisesti otsikosta. Jos muutat teknistä nimeä julkaisun jälkeen, muista luoda tarvittavat uudelleenohjaukset.', max_length=63, validators=[django.core.validators.RegexValidator(message='Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.', regex='[a-z0-9-]+')], verbose_name='Tekninen nimi')),
                ('path', models.CharField(help_text='Polku määritetään automaattisesti teknisen nimen perusteella.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(message='Polku saa sisältää vain pieniä kirjaimia, numeroita, väliviivoja sekä kauttaviivoja.', regex='[a-z0-9-/]+')], verbose_name='Polku')),
                ('title', models.CharField(help_text='Otsikko näytetään automaattisesti sivun ylälaidassa sekä valikossa.', max_length=1023, verbose_name='Otsikko')),
                ('description', models.TextField(blank=True, default='', help_text='Näkyy mm. hakukoneille sekä RSS-asiakasohjelmille.', verbose_name='Kuvaus')),
                ('body', models.TextField(blank=True, default='', help_text='Albumilla voi olla tekstisisältöä, jolloin se näytetään albuminäkymän yläosassa ennen ala-albumeja ja kuvia.', verbose_name='Tekstisisältö')),
                ('is_public', models.BooleanField(default=True, help_text='Ei-julkiset albumit näkyvät vain ylläpitokäyttäjille.', verbose_name='Julkinen')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Albumi',
                'verbose_name_plural': 'Albumit',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('src', models.ImageField(height_field='height', max_length=255, null=True, upload_to='', width_field='width')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='MediaSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_width', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
                ('quality', models.PositiveIntegerField()),
                ('is_default_thumbnail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, help_text='Tekninen nimi eli "slug" näkyy URL-osoitteissa. Sallittuja merkkejä ovat pienet kirjaimet, numerot ja väliviiva. Jos jätät teknisen nimen tyhjäksi, se generoidaan automaattisesti otsikosta. Jos muutat teknistä nimeä julkaisun jälkeen, muista luoda tarvittavat uudelleenohjaukset.', max_length=63, validators=[django.core.validators.RegexValidator(message='Tekninen nimi saa sisältää vain pieniä kirjaimia, numeroita sekä väliviivoja.', regex='[a-z0-9-]+')], verbose_name='Tekninen nimi')),
                ('order', models.IntegerField(default=0, help_text='Saman yläsivun alaiset sivut järjestetään valikossa tämän luvun mukaan nousevaan järjestykseen (pienin ensin).', verbose_name='Järjestys')),
                ('path', models.CharField(help_text='Polku määritetään automaattisesti teknisen nimen perusteella.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(message='Polku saa sisältää vain pieniä kirjaimia, numeroita, väliviivoja sekä kauttaviivoja.', regex='[a-z0-9-/]+')], verbose_name='Polku')),
                ('title', models.CharField(help_text='Otsikko näytetään automaattisesti sivun ylälaidassa sekä valikossa.', max_length=1023, verbose_name='Otsikko')),
                ('description', models.TextField(blank=True, default='', help_text='Näkyy mm. hakukoneille sekä RSS-asiakasohjelmille.', verbose_name='Kuvaus')),
                ('is_public', models.BooleanField(default=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='edegal.Album')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ('album', 'order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='Used for de-duplication. Kindly please do not change.', max_length=64, verbose_name='Digest')),
                ('text', models.TextField(blank=True, default='', help_text='Keep this short enough to fit in a small modal dialog and use the URL field for full license text.', verbose_name='Terms and conditions text')),
                ('is_public', models.BooleanField(default=True, help_text='Public T&Cs can be selected by any user at upload time. Use public T&Cs for eg. Creative Commons licenses, "All Rights Reserved" and other common situations. Private T&Cs can only be selected by the owner.', verbose_name='Public')),
                ('url', models.CharField(blank=True, default='', help_text='If these terms and conditions refer to a publicly known content license, such as Creative Commons, please link to it here.', max_length=255, verbose_name='License URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms and conditions',
                'verbose_name_plural': 'Terms and conditions',
            },
            bases=(models.Model, edegal.models.terms_and_conditions.DedupMixin),
        ),
        migrations.AddField(
            model_name='media',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='edegal.Picture'),
        ),
        migrations.AddField(
            model_name='media',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edegal.MediaSpec'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edegal.Picture'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Tämä albumi luodaan valitun albumin alaisuuteen. Juurialbumilla ei ole yläalbumia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='edegal.Album', verbose_name='Yläalbumi'),
        ),
        migrations.AddField(
            model_name='album',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edegal.TermsAndConditions'),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set([('album', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='picture',
            index_together=set([('album', 'order', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('parent', 'slug')]),
        ),
    ]
