# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edegal.models.terms_and_conditions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edegal', '0002_auto_20170411_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='Used for de-duplication. Kindly please do not change.', max_length=64, verbose_name='Digest')),
                ('text', models.TextField(blank=True, default='', help_text='Keep this short enough to fit in a small modal dialog and use the URL field for full license text.', verbose_name='Terms and conditions text')),
                ('is_public', models.BooleanField(default=True, help_text='Public T&Cs can be selected by any user at upload time. Use public T&Cs for eg. Creative Commons licenses, "All Rights Reserved" and other common situations. Private T&Cs can only be selected by the owner.', verbose_name='Public')),
                ('url', models.CharField(blank=True, default='', help_text='If these terms and conditions refer to a publicly known content license, such as Creative Commons, please link to it here.', max_length=255, verbose_name='License URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms and conditions',
                'verbose_name_plural': 'Terms and conditions',
            },
            bases=(models.Model, edegal.models.terms_and_conditions.DedupMixin),
        ),
        migrations.AddField(
            model_name='album',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edegal.TermsAndConditions'),
        ),
        migrations.AddField(
            model_name='picture',
            name='override_terms_and_conditions',
            field=models.ForeignKey(blank=True, help_text='Terms and conditions are normally set on a per-album basis. However, you can override the terms and conditions on a per-picture basis here.', null=True, on_delete=django.db.models.deletion.CASCADE, to='edegal.TermsAndConditions', verbose_name='Override terms and conditions'),
        ),
    ]
