# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0003_auto_20180217_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaspec',
            name='format',
            field=models.CharField(default='jpeg', max_length=4),
        ),
    ]
