# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0003_auto_20170413_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='override_terms_and_conditions',
        ),
    ]
