# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0004_mediaspec_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='format',
            field=models.CharField(default='jpeg', max_length=4),
        ),
        migrations.AddField(
            model_name='media',
            name='role',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('preview', 'Preview'), ('original', 'Original')], default='thumbnail', max_length=9),
        ),
        migrations.AddField(
            model_name='mediaspec',
            name='role',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('preview', 'Preview')], default='thumbnail', max_length=9),
        ),
    ]
