# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0004_remove_picture_override_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('album', 'order', 'slug'), 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterIndexTogether(
            name='picture',
            index_together=set([('album', 'order', 'slug')]),
        ),
    ]
