# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0006_populate_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaspec',
            name='is_default_thumbnail',
        ),
        migrations.AlterField(
            model_name='media',
            name='role',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('preview', 'Preview'), ('original', 'Original')], max_length=9),
        ),
        migrations.AlterField(
            model_name='media',
            name='src',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
