# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 15:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0011_auto_20180922_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterField(
            model_name='album',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Will be displayed at the top of the album view before subalbums and pictures.', verbose_name='Text content'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default='', help_text='While the description is not usually displayed in the user interface, it is visible to search engines and RSS readers. If your item contains text content, a good practice is to make the description a short summary of the content.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Items that are not public are only displayed to admin users.', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The album under which this album will reside. The root album (/) has no parent album.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='edegal.Album', verbose_name='Parent Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='path',
            field=models.CharField(help_text='Will be automatically determined from parent and slug.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(message='The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/).', regex='[a-z0-9-/]+')], verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='[a-z0-9-]+')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='The title will be displayed at the top of the view.', max_length=1023, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, default='', help_text='While the description is not usually displayed in the user interface, it is visible to search engines and RSS readers. If your item contains text content, a good practice is to make the description a short summary of the content.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='order',
            field=models.IntegerField(default=0, help_text='The child items of a common parent are ordered in an ascending order by this number (smallest first).', verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(help_text='Will be automatically determined from parent and slug.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(message='The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/).', regex='[a-z0-9-/]+')], verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='[a-z0-9-]+')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(help_text='The title will be displayed at the top of the view.', max_length=1023, verbose_name='Title'),
        ),
    ]
