# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0013_auto_20181223_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='level',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='album',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The album under which this album will reside. The root album (/) has no parent album.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='edegal.Album', verbose_name='Parent Album'),
        ),
    ]
