# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0014_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='layout',
            field=models.CharField(choices=[('simple', 'Simple'), ('yearly', 'Yearly')], default='simple', max_length=6),
        ),
    ]
