# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-09 13:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edegal', '0019_auto_20190623_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edegal.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='[a-z0-9-]+')], verbose_name='Slug')),
                ('title', models.CharField(help_text='The title will be displayed at the top of the view.', max_length=1023, verbose_name='Title')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Pictures with sensitive tags will show a content warning.')),
                ('is_visible', models.BooleanField(default=True, help_text='Items that are not visible are not displayed in listings, but they can still be accessed via exact URL.', verbose_name='Visible')),
            ],
        ),
        migrations.AddField(
            model_name='picturetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edegal.Tag'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(related_name='pictures', through='edegal.PictureTag', to='edegal.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='picturetag',
            unique_together=set([('picture', 'tag')]),
        ),
        migrations.AlterIndexTogether(
            name='picturetag',
            index_together=set([('tag', 'picture')]),
        ),
    ]
