# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0019_auto_20190623_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='Controls whether or not site visitors can download original photos from this album, or the whole album as a zip file.'),
        ),
    ]
