# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0020_album_is_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='cover_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edegal.Picture'),
        ),
    ]
