# Generated by Django 3.0.7 on 2020-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0024_auto_20200927_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='flickr_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
