# Generated by Django 4.2.3 on 2023-07-26 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import edegal.models.import_job


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("edegal", "0025_photographer_flickr_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="path",
            field=models.CharField(
                help_text="Will be automatically determined from parent and slug.",
                max_length=1023,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_path",
                        message="The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).",
                        regex="^/[a-z0-9-/]*$",
                    )
                ],
                verbose_name="Path",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="path",
            field=models.CharField(
                help_text="Will be automatically determined from parent and slug.",
                max_length=1023,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_path",
                        message="The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).",
                        regex="^/[a-z0-9-/]*$",
                    )
                ],
                verbose_name="Path",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="path",
            field=models.CharField(
                help_text="Will be automatically determined from parent and slug.",
                max_length=1023,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_path",
                        message="The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).",
                        regex="^/[a-z0-9-/]*$",
                    )
                ],
                verbose_name="Path",
            ),
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "user_input",
                    models.TextField(
                        help_text="URLs to import, one per line. At the moment only Flickr albums are supported."
                    ),
                ),
                (
                    "leaf_album_title",
                    models.CharField(
                        blank=True,
                        help_text="If set, imported albums will have a two-level hierarchy with the parent album title derived from the name of the imported album and the leaf album having this name. If unset, the imported album will be created directly under the parent album with its original title. In the larppikuvat.fi convention, set this to the name of the photographer.",
                        max_length=1023,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_album",
                    models.ForeignKey(
                        default=edegal.models.import_job.get_root_album,
                        help_text="Imported albums will be created under this album. In the larppikuvat.fi convention, leave this as the root album.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="edegal.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportItem",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("source_id", models.CharField(max_length=1023)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("flickr", "Flickr album")], max_length=7
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        help_text="The album that was created for this import item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="edegal.album",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="edegal.importjob"),
                ),
            ],
            options={
                "unique_together": {("import_job", "source_id")},
            },
        ),
    ]
