# Generated by Django 3.0.7 on 2020-09-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edegal', '0025_photographer_flickr_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarppikuvatPhotographerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
                ('delivery_schedule', models.TextField(blank=True)),
                ('delivery_practice', models.TextField(blank=True)),
                ('delivery_method', models.TextField(blank=True)),
                ('copy_protection', models.TextField(blank=True)),
                ('expected_compensation', models.TextField(blank=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='larppikuvat_profile', to='edegal.Photographer')),
            ],
        ),
    ]
