hostname: larppikuvat.fi
mediaNfs:
  server: 91.105.252.80
  path: /opt/conikuvat/larppikuvat
kompassi:
  baseUrl: https://kompassi.eu
  photographerGroup: larppikuvat-staff
  adminGroup: larppikuvat-admins
mail:
  smtpHostname: sr1.pahaip.fi
  smtpPort: 25
  sender: root@tracon.fi
  from: Larppikuvat.fi <root@tracon.fi>
# Secret `v4` in namespace larppikuvat-v4 is managed out of band.
existingSecretName: v4
