hostname: conikuvat.fi
legacy:
  namespace: conikuvat-production
mediaNfs:
  server: 91.105.252.80
  path: /opt/conikuvat
kompassi:
  baseUrl: https://kompassi.eu
  photographerGroup: conikuvat-staff
  adminGroup: conikuvat-admins
mail:
  smtpHostname: sr1.pahaip.fi
  smtpPort: 25
  sender: root@tracon.fi
  from: Conikuvat.fi <root@tracon.fi>
# Secret `v4` in namespace conikuvat-v4 is managed out of band.
existingSecretName: v4
