name: cicd

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      SKAFFOLD_DEFAULT_REPO: harbor.con2.fi/con2
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'      
      - uses: pairity/setup-cd-tools@30acb848f9ff747aff4810dac40c5cc0971f485d
        with:
          kubectl: '1.20.4'
          skaffold: '1.20.0'         
      - uses: docker/login-action@v1
        with:
          registry: harbor.con2.fi
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: docker/setup-buildx-action@v1          
      - run: python3 -m pip install emskaffolden
      - run: emskaffolden -E staging -- run -n conikuvat-staging
