name: cicd

on:
  push:
    branches:
      - gha-test


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta (Backend)
        id: docker_meta_backend
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: harbor.con2.fi/con2/edegal
      - name: Docker meta (Frontend)
        id: docker_meta_frontend
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: harbor.con2.fi/con2/edegal-frontend
      - name: Docker meta (Frontend static)
        id: docker_meta_static
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: harbor.con2.fi/con2/edegal-static

      - name: Login to Con2 Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.con2.fi
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_backend.outputs.tags }}
          labels: ${{ steps.docker_meta_backend.outputs.labels }}
      - name: Build frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_frontend.outputs.tags }}
          labels: ${{ steps.docker_meta_frontend.outputs.labels }}
      - name: Build static
        id: docker_build_static
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: frontend/Dockerfile.static
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_static.outputs.tags }}
          labels: ${{ steps.docker_meta_static.outputs.labels }}
          build-args: |
            FRONTEND_IMAGE=harbor.con2.fi/con2/edegal-frontend@${{ steps.docker_build_frontend.outputs.digest }}
            BACKEND_IMAGE=harbor.con2.fi/con2/edegal@${{ steps.docker_build_backend.outputs.digest }}
