name: development

on:
  push:
    branches:
      - gha-test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: harbor.con2.fi
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}        
      - name: Build backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: harbor.con2.fi/con2/edegal:gha-test
      - name: Build backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: harbor.con2.fi/con2/edegal-frontend:gha-test          