apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: edegal
    component: postgres
  name: postgres-data
spec:
  storageClass: !Var postgres_storage_pvc_storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
