apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    stack: edegal
    component: postgres
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
data:
  username: !Base64,Var postgres_username
  hostname: !Base64,Var postgres_hostname
  database: !Base64,Var postgres_database