apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    stack: edegal
    component: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    stack: edegal
    component: postgres
