# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0010_auto_20180919_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='src',
            field=models.FileField(max_length=1023, unique=True, upload_to=''),
        ),
    ]
