# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0012_auto_20180922_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Items that are not visible are not displayed in listings, but they can still be accessed via exact URL.', verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='album',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='If set, users that stumble upon this album will be redirected to this URL.', max_length=1023, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Items that are not public are only accessible to admin users.', verbose_name='Public'),
        ),
    ]
