# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 09:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edegal', '0016_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='[a-z0-9-]+')], verbose_name='Slug')),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('homepage_url', models.CharField(blank=True, max_length=255)),
                ('twitter_handle', models.CharField(blank=True, max_length=15)),
                ('instagram_handle', models.CharField(blank=True, max_length=30)),
                ('facebook_handle', models.CharField(blank=True, max_length=50)),
                ('default_terms_and_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edegal.TermsAndConditions')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='album',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_albums', to='edegal.Photographer'),
        ),
        migrations.AddField(
            model_name='album',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='edegal.Photographer'),
        ),
    ]
