# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0017_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='email',
            field=models.EmailField(blank=True, help_text='This e-mail address will be offered as a contact point for users who want to request permission to use your photos for purposes other than those covered by the terms and conditions.', max_length=254),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public T&Cs can be selected by any user at upload time. Use public T&Cs for eg. Creative Commons licenses, "All Rights Reserved" and other common situations. Private T&Cs can only be selected by the owner.', verbose_name='Public'),
        ),
    ]
