# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-12 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0022_photographer_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='taken_at',
            field=models.DateTimeField(blank=True, help_text='EXIF original date time of the original media', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='path',
            field=models.CharField(help_text='Will be automatically determined from parent and slug.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_path', message='The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).', regex='^/[a-z0-9-/]+$')], verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='^[a-z0-9-]+$')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='^[a-z0-9-]+$')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(help_text='Will be automatically determined from parent and slug.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_path', message='The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).', regex='^/[a-z0-9-/]+$')], verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='^[a-z0-9-]+$')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='series',
            name='path',
            field=models.CharField(help_text='Will be automatically determined from parent and slug.', max_length=1023, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_path', message='The path may only contain lower case letters (a–z), numbers (0–9), dashes (-) and forward slashes (/). The path must start with a slash (/).', regex='^/[a-z0-9-/]+$')], verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug will be included as part of the URL. The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-). If you leave the slug blank, it will be generated from the title. If you change the slug after publishing, remember to create any redirects you may need.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='The slug may only contain lower case letters (a–z), numbers (0–9) and dashes (-).', regex='^[a-z0-9-]+$')], verbose_name='Slug'),
        ),
    ]
