# Generated by Django 3.0.7 on 2020-09-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edegal', '0023_auto_20200212_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('album', 'order', 'taken_at', 'slug'), 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
    ]
