# Generated by Django 4.2.3 on 2024-08-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edegal", "0026_alter_album_path_alter_picture_path_and_more"),
    ]

    operations = [
        # XXX(django-5.1): corresponding AlterIndexTogether commented out in 0001_initial because it breaks in Django 5.1
        migrations.RunSQL(
            sql="drop index if exists edegal_picture_album_id_order_slug_117e4cf9_idx",
        ),
        migrations.AlterField(
            model_name="picture",
            name="album",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="edegal.album",
            ),
        ),
        migrations.AddIndex(
            model_name="picture",
            index=models.Index(
                fields=["album", "order", "taken_at", "slug"],
                name="edegal_pict_album_i_145fe8_idx",
            ),
        ),
    ]
